parameters:
#    nulli_forum.example.class: Nulli\ForumBundle\Example

services:
#    nulli_forum.example:
#        class: %nulli_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
